Repository bee-travels/bee-travels-node, pull requests merged in 2020-02, with the labels that each got.

#88 Gs bug 87
  src/currencyexchange/.gitignore
  src/currencyexchange/README.md
  src/currencyexchange/package-lock.json
  src/currencyexchange/package.json
  src/currencyexchange/src/app.js
  src/currencyexchange/src/services/serviceHandler.js
  src/currencyexchange/src/services/serviceHandler.test.js
  src/currencyexchange/swagger.yaml
Labels: Currency Exchange Service, v1

#84 MERGE IT MAXXXXXX NOWWWWWW
  .gitignore
  run-all.sh
  src/destination/public/.DS_Store
  src/destination/public/images/Beirut, Lebanon.jpg
  src/destination/public/images/Jaipur, India.jpg
  src/destination/public/images/Jaipur, India.png
  src/ui/client/package.json
  src/ui/client/public/android-chrome-192x192.png
  src/ui/client/public/apple-touch-icon.png
  src/ui/client/public/browserconfig.xml
  src/ui/client/public/favicon-16x16.png
  src/ui/client/public/favicon-32x32.png
  src/ui/client/public/favicon.ico
  src/ui/client/public/ibm bee.png
  src/ui/client/public/index.html
  src/ui/client/public/mstile-150x150.png
  src/ui/client/public/safari-pinned-tab.svg
  src/ui/client/public/site.webmanifest
  src/ui/client/src/App.js
  src/ui/client/src/components/BookingLayout/BookingFragment/BookingFragment.js
  src/ui/client/src/components/BookingLayout/BookingFragment/BookingFragment.module.css
  src/ui/client/src/components/BookingLayout/BookingLayout.js
  src/ui/client/src/components/BookingLayout/DestinationFragment/DestinationFragment.js
  src/ui/client/src/components/BookingLayout/DestinationFragment/DestinationFragment.module.css
  src/ui/client/src/components/BookingLayout/DestinationFragment/SearchBar.module.css
  src/ui/client/src/components/Content.js
  src/ui/client/src/components/Error.js
  src/ui/client/src/components/ErrorLayout/ErrorLayout.js
  src/ui/client/src/components/Home.js
  src/ui/client/src/components/HomeLayout/HomeLayout.js
  src/ui/client/src/components/HomeLayout/HomeLayout.module.css
  src/ui/client/src/components/HomeLayout/SearchBar.module.css
  src/ui/client/src/components/common/BeeLogo.js
  src/ui/client/src/components/common/DestinationFragment.module.css
  src/ui/client/src/components/common/DoubleSlider.js
  src/ui/client/src/components/common/HideAndSeekSearch.js
  src/ui/client/src/components/common/UncontrolledSearch.js
  src/ui/client/src/components/common/slider.css
  src/ui/client/src/fonts.css
  src/ui/client/src/ibmcloud.css
  src/ui/client/src/index.css
  src/ui/client/src/index.js
  src/ui/client/src/react-app-env.d.ts
  src/ui/client/tsconfig.json
  src/ui/client/yarn.lock
  src/ui/index.js
Labels: Front End, v1

#95 Docker Files
  docker-compose.yml
  src/hotel/Dockerfile
Labels: v1

#96 added test, updated npm modules, fixed run all script
  .gitignore
  .travis.yml
  run-all.sh
  src/currencyexchange/package.json
  src/hotel/package.json
  src/ui/client/package-lock.json
  src/ui/client/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: v1

#111 Documentation
  README.md
  readme-images/architecturev1.jpg
  readme-images/logo.jpg
  readme-images/screenshot.jpg
  src/currencyexchange/README.md
  src/currencyexchange/readme-images/apis.jpg
  src/currencyexchange/swagger.yaml
  src/destination/README.md
  src/destination/package.json
  src/destination/readme-images/apis.jpg
  src/destination/swagger.yaml
  src/hotel/README.md
  src/hotel/package.json
  src/hotel/readme-images/apis.jpg
  src/hotel/swagger.yaml
  src/ui/README.md
  src/ui/package.json
  src/ui/readme-images/booking.jpg
  src/ui/readme-images/home.jpg
Labels: v1
